### ISSUE TITLE
configure the awstats MultiSite

### ISSUE THREAD

**Issue by Andresferreira3191** [manics/docker-awstats#8]
I have:
site1 (container1)
site2 (container2)
site3 (container3)
awstats (container4)
How would you configure the awstats to see the statistics of each site?

**Comment by manics** [comment]
@Andresferreira3191 we don't use Awstats on multiple sites at the same time. If we have multiple servers we run one Awstats instance per set of logs.

If you want to stay with a single Awstats instance the Awstats docs should explain how to set up multiple sites. If you find a working configuration please let us know, either by opening a PR if you can add the configuration without any breaking changes, or as a link to your repository.

**Comment by manics** [comment]
Closing, no response.
